image:  registry.gitlab.com/pages/hugo/hugo_extended:0.74.3
variables:
    GIT_SUBMODULE_STRATEGY: recursive
pages:
    script:
        - npm install postcss-cli
        - npm install autoprefixer
        - hugo
    artifacts:
        paths:
        - public
    only:
    - master